// Esse exemplo demonstra o erro tentar chamar uma funÃ§Ã£o com mais argumentos do que o definido

routine teste;

fn foo(int a) -> int {
  return a;
}

begin
fn main() -> int {
  int a = foo(1,2,3);

  return 1;
}